In [ ]:
# Importando
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix


np.random.seed(42)


num_classes = 3  # Classes de chance de chuva: 0 (baixa), 1 (média), 2 (alta)
num_features = 4
num_samples = 150

# dados sintéticos
X = np.vstack([
    np.random.normal(loc=i, scale=0.5, size=(num_samples // num_classes, num_features))
    for i in range(num_classes)
])
y = np.hstack([[i] * (num_samples // num_classes) for i in range(num_classes)])

# (80% treino, 20% teste)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# KNN e o número de vizinhos
knn = KNeighborsClassifier(n_neighbors=3)

# Treinando o modelo com os dados de treino
knn.fit(X_train, y_train)

# Realizando previsões nos dados de teste
y_pred = knn.predict(X_test)


print("Previsões para os 5 primeiros dados de teste:", y_pred[:5])

# Calculos
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

# Exibindo os resultados
print(f'Acurácia: {accuracy * 100:.2f}%')
print(f'Precisão: {precision * 100:.2f}%')
print(f'Recall (Sensibilidade): {recall * 100:.2f}%')

# Matriz de confusão
print("Matriz de Confusão:")
print(confusion_matrix(y_test, y_pred))

# previsão condição climática
nova_condicao = np.array([[1.5, 2.0, 1.8, 2.2]])  # Características simuladas ------>>>>>(temperatura, umidade, vento, pressão)
chance_de_chuva_predita = knn.predict(nova_condicao)
print("Previsão de chance de chuva para a nova condição:", chance_de_chuva_predita[0])

# Chance de Chuva
chances_de_chuva = {0: 'Baixa', 1: 'Média', 2: 'Alta'}
y_pred_nomes = [chances_de_chuva[label] for label in y_pred]

# Exibindo as previsões de chuva para os primeiros 5 dados
print("\nPrevisões de chuva para os 5 primeiros dados de teste:")
for i, previsao in enumerate(y_pred_nomes[:5]):
    print(f"Previsão {i+1}: {previsao}")


Previsões para os 5 primeiros dados de teste: [1 0 2 2 1]
Acurácia: 96.67%
Precisão: 96.94%
Recall (Sensibilidade): 96.67%
Matriz de Confusão:
[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
Previsão de chance de chuva para a nova condição: 2

Previsões de chuva para os 5 primeiros dados de teste:
Previsão 1: Média
Previsão 2: Baixa
Previsão 3: Alta
Previsão 4: Alta
Previsão 5: Média
